spring:
  datasource:
    url: jdbc:h2:file:~/invoiceflow-db/demo;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console       # http://localhost:8080/h2-console

app:
  backend-base-url: http://localhost:8080
  frontend-base-url: http://localhost:5173
  qbo:
    bypass: true